services:
  back-end:
    build:
      context: back-end
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      spring.profiles.active: prod
      # DB_URL: jdbc:mysql://mysql-server/spring_assignment_submission
      DB_USERNAME: root
      DB_PASSWORD: password123
    depends_on:
      - mysql-server
    networks:
      - submission-app
    
  front-end:
    build:
      context: front-end
      dockerfile: Dockerfile
    expose:
      - "3000"
    ports:
      - 3000:3000
    depends_on:
      - back-end
    networks:
      - submission-app
  
  mysql-server:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: spring_assignment_submission
      MYSQL_ROOT_PASSWORD: password123
    
    networks:
      - submission-app

  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - front-end
    networks:
      - submission-app

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf:/etc/letsencrypt
    command:
#      - renew
       - certonly
       - --webroot
       - -w
       - /var/www/certbot/
       - --email=trevor@coderscampus.com
       - --agree-tos
       - --no-eff-email
       - -d
       - cod3rscampus.com
       
volumes:
  dbdata:

networks:
  submission-app:
  
